import javax.swing.*;

public class NewJFrame extends javax.swing.JFrame {

    DefaultListModel model1 = new DefaultListModel();

    DefaultListModel model2 = new DefaultListModel();

    DefaultListModel model3 = new DefaultListModel();
    Users user = null;

    public NewJFrame() {

        initComponents();
        text1.setModel(model1);
        text2.setModel(model2);
        text3.setModel(model3);
    }
    public void UsersEkle(Users user){

        this.user = user;

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        text2 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        text1 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        text3 = new javax.swing.JList<>();
        butonilgialani = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KULLANİCİ TWEETLET TAKİPÇİLER VE TAKİP EDİLENLER");
        setBounds(new java.awt.Rectangle(200, 200, 0, 0));

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 51, 0));
        jLabel1.setText("TWEETLER");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 51, 0));
        jLabel2.setText("TAKİP EDİLENLER");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 51, 0));
        jLabel3.setText("TAKİPÇİLER");

        jButton1.setBackground(new java.awt.Color(102, 255, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 0, 0));
        jButton1.setText("VERİLERİ GÖSTER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(text2);

        jScrollPane2.setViewportView(text1);

        jScrollPane3.setViewportView(text3);

        butonilgialani.setBackground(new java.awt.Color(102, 255, 0));
        butonilgialani.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        butonilgialani.setForeground(new java.awt.Color(255, 0, 0));
        butonilgialani.setText("FAVORİ İLGİ ALANLARINI GÖSTER");
        butonilgialani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonilgialaniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(107, 107, 107)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addComponent(butonilgialani, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(210, 210, 210)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(667, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel1)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jLabel3))
                                                .addGap(18, 18, 18)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(butonilgialani, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addContainerGap(66, Short.MAX_VALUE)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(59, 59, 59)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {

        Users user = this.user;
        int sayi = 1;
        for(String AA:user.getTweetler()){
            model1.addElement(sayi + "-"+AA);
            sayi++;
        }


        sayi = 1;
        for (String AA:user.getTakipciler()){
            model2.addElement(sayi + "-"+AA);
            sayi++;
        }


        sayi = 1;
        for (String AA:user.getTakipEdilenler()){
            model3.addElement(sayi + "-"+AA);
            sayi++;
        }




    }

    private void butonilgialaniActionPerformed(java.awt.event.ActionEvent evt) {

        Users user = this.user;

        String message = null;

        BizimArraylist<String> tweetler = user.getTweetler();

        BizimArraylist<String> parcatweetler = new BizimArraylist<>();
        BizimArraylist<String> parcatweetsayisi = new BizimArraylist<>();

        BizimHashMap<String,Integer> hashMapimiz = new BizimHashMap<>();

        for(String AA:tweetler){

            String[] kelimeler = AA.split(" ");
            if(kelimeler.length == 1){
                parcatweetler.add(AA);
                continue;
            }
            for(String BB:kelimeler){
                if (BB.contains("#")){
                    continue;
                }
                parcatweetler.add(BB);
            }


        }




for (String HH:parcatweetler){

    Integer kelimeninsayisi = 0;

    for (String GG:tweetler){

        String[] kelimeler = GG.split(" ");
        for (String TT:kelimeler){

            if (TT.equals(HH)){

                kelimeninsayisi++;

            }

        }



    }

parcatweetsayisi.add(String.valueOf(kelimeninsayisi));


hashMapimiz.put(HH,kelimeninsayisi);


}



int sayi1 = 0;
int sayi2 = 0;
int[] indexleri = new int[5];
int indexTT = 0;

for(int yy = 0; yy < 5; yy++){


    for (int k = 0; k < parcatweetler.size();k++){

        sayi1 = Integer.parseInt(parcatweetsayisi.get(k));


        System.out.println(parcatweetler.get(k) +" "+parcatweetsayisi.get(k));

        boolean kontrol = false;

        for (int ll = 0; ll < yy ; ll++){

            if(parcatweetler.get(indexleri[ll]).equals(parcatweetler.get(k))){
                kontrol = true;
                break;
            }
        }
        if(kontrol){
            continue;
        }
        if(sayi1 > sayi2){
            sayi2 = sayi1;
            indexTT = k;
        }
    }
    sayi1 = 0;
    sayi2 = 0;

    indexleri[yy] = indexTT;

}

for (int ii = 0; ii < 5;ii++){
    System.out.println(indexleri[ii] +"...............");
}

message = parcatweetler.get(indexleri[0]) + "\n" +  parcatweetler.get(indexleri[1]) + "\n" +  parcatweetler.get(indexleri[2]) + "\n" +  parcatweetler.get(indexleri[3]) + "\n" +  parcatweetler.get(indexleri[4]);

        JOptionPane.showMessageDialog(null, message, "FAVORİ İLGİ ALANLARI", JOptionPane.WARNING_MESSAGE);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton butonilgialani;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> text1;
    private javax.swing.JList<String> text2;
    private javax.swing.JList<String> text3;
    // End of variables declaration
}
